name: Mirror and Verify

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml', '**/*.yml', '**/*.target') }}
        restore-keys: ${{ runner.os }}-m2-
    - name: Cache Mirror
      uses: actions/cache@v2
      with:
        path: ~/eclipse-mirrors
        key: ${{ runner.os }}-p2-mirror-${{ hashFiles('**/pom.xml', '**/*.target') }}
        # the key match must be perfect:
        # if we change the mirror or the tp we invalidate the cache
    - name: Build the Mirror
      run: mvn package
      working-directory: tycho-mirrors
    - name: Verify the TP against the Mirror
      run: mvn target-platform-validation:validate-target-platform@validate-target-platform
      working-directory: tycho-mirrors
    - name: Show output contents
      run: tree ~/eclipse-mirrors
      if: runner.os == 'Linux'
